#!/usr/bin/env bash
set -euo pipefail

remote="${REMOTE:-ubuntu@london}"
remote_dir="${REMOTE_DIR:-/opt/audiobookshelf-monitor}"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
temporary_remote=""

cleanup() {
  if [[ -n "$temporary_remote" ]]; then
    # temporary_remote is generated by mktemp on the remote host.
    # shellcheck disable=SC2029
    ssh "$remote" "rm -rf '$temporary_remote'" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

[[ "$remote_dir" =~ ^/[A-Za-z0-9._/-]+$ ]] || {
  printf 'invalid REMOTE_DIR: %s\n' "$remote_dir" >&2
  exit 1
}

required_files=(
  "$script_dir/check.sh"
  "$script_dir/systemd/audiobookshelf-monitor.service"
  "$script_dir/systemd/audiobookshelf-monitor.timer"
)
for path in "${required_files[@]}"; do
  [[ -f "$path" ]] || {
    printf 'missing required file: %s\n' "$path" >&2
    exit 1
  }
done

bash -n "$script_dir/check.sh"
for command_name in scp ssh; do
  command -v "$command_name" >/dev/null 2>&1 || {
    printf 'missing required command: %s\n' "$command_name" >&2
    exit 1
  }
done

temporary_remote="$(ssh "$remote" 'mktemp -d /tmp/audiobookshelf-monitor.XXXXXX')"
scp "$script_dir/check.sh" "$remote:$temporary_remote/check.sh"
scp "$script_dir/systemd/"* "$remote:$temporary_remote/"

# remote_dir is validated above; temporary_remote is generated remotely.
# shellcheck disable=SC2029
ssh "$remote" \
  "REMOTE_DIR='$remote_dir' TEMPORARY_REMOTE='$temporary_remote' bash -s" <<'REMOTE_SCRIPT'
set -euo pipefail

: "${REMOTE_DIR:?missing REMOTE_DIR}"
: "${TEMPORARY_REMOTE:?missing TEMPORARY_REMOTE}"

for command_name in curl jq openssl systemd-analyze timeout; do
  command -v "$command_name" >/dev/null 2>&1 || {
    printf 'missing required remote command: %s\n' "$command_name" >&2
    exit 1
  }
done

sudo install -d -m 0755 "$REMOTE_DIR"
sudo install -m 0755 "$TEMPORARY_REMOTE/check.sh" "$REMOTE_DIR/check.sh"
systemd-analyze verify \
  "$TEMPORARY_REMOTE/audiobookshelf-monitor.service" \
  "$TEMPORARY_REMOTE/audiobookshelf-monitor.timer"
sudo install -m 0644 \
  "$TEMPORARY_REMOTE/audiobookshelf-monitor.service" \
  /etc/systemd/system/audiobookshelf-monitor.service
sudo install -m 0644 \
  "$TEMPORARY_REMOTE/audiobookshelf-monitor.timer" \
  /etc/systemd/system/audiobookshelf-monitor.timer

sudo systemctl daemon-reload
sudo systemctl enable --now audiobookshelf-monitor.timer
sudo systemctl start audiobookshelf-monitor.service
systemctl is-active --quiet audiobookshelf-monitor.timer
systemctl list-timers audiobookshelf-monitor.timer --no-pager
REMOTE_SCRIPT
