[CmdletBinding()]
param(
  [switch]$SkipInstall,
  [string]$CursorRoot,
  [string]$CacheRoot,
  [switch]$NoActivate
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'windows-lib.ps1')
Assert-Windows

if ($SkipInstall) {
  Write-Host 'Skipping cursor installation because -SkipInstall was passed.'
  return
}

if ([string]::IsNullOrWhiteSpace($CacheRoot)) {
  $CacheRoot = Get-WindowsSetupCacheDirectory
}

if ([string]::IsNullOrWhiteSpace($CursorRoot)) {
  $localAppData = [Environment]::GetEnvironmentVariable('LOCALAPPDATA')
  if ([string]::IsNullOrWhiteSpace($localAppData)) {
    throw 'LOCALAPPDATA is not set.'
  }

  $CursorRoot = Join-Path $localAppData 'Microsoft\Windows\Cursors\Bibata-Modern-Ice'
}

$script:CursorRoot = $CursorRoot
$script:NoActivate = $NoActivate.IsPresent
$script:CursorRegistry = 'HKCU:\Control Panel\Cursors'
$script:CursorRegistryChanged = $false

New-Item -ItemType Directory -Path $script:CursorRoot -Force | Out-Null

$cursorCache = Join-Path $CacheRoot 'cursors'
$archiveCache = Join-Path $cursorCache 'archives'
$extractRoot = Join-Path $cursorCache 'expanded'
$script:BibataCursorVersion = 'v2.0.7'
$script:BibataExpectedSourceDirectoryName = 'Bibata-Modern-Ice-Regular-Windows'
$bibataArchiveUri = "https://github.com/ful1e5/Bibata_Cursor/releases/download/$script:BibataCursorVersion/Bibata-Modern-Ice-Windows.zip"
$archivePath = Join-Path $archiveCache "Bibata-Modern-Ice-Windows-$script:BibataCursorVersion.zip"
$extractPath = Join-Path $extractRoot "Bibata-Modern-Ice-Windows-$script:BibataCursorVersion"

$cursorMap = @{
  Arrow       = 'arrow.cur'
  Help        = 'help.cur'
  AppStarting = 'working.ani'
  Wait        = 'busy.ani'
  Crosshair   = 'cross.cur'
  IBeam       = 'beam.cur'
  NWPen       = 'pen.cur'
  No          = 'unavailable.cur'
  SizeNS      = 'size_ns.cur'
  SizeWE      = 'size_we.cur'
  SizeNWSE    = 'size_nwse.cur'
  SizeNESW    = 'size_nesw.cur'
  SizeAll     = 'move.cur'
  UpArrow     = 'up.cur'
  Hand        = 'link.cur'
}

# Upstream Windows packages currently ship PascalCase cursor filenames generated by clickgen.
# Keep registry-facing target names stable with this normalization map.
$sourceCursorMap = @{
  'arrow.cur'       = 'Pointer.cur'
  'help.cur'        = 'Help.cur'
  'working.ani'     = 'Work.ani'
  'busy.ani'        = 'Busy.ani'
  'cross.cur'       = 'Cross.cur'
  'beam.cur'        = 'Text.cur'
  'pen.cur'         = 'Handwriting.cur'
  'unavailable.cur' = 'Unavailable.cur'
  'size_ns.cur'     = 'Vert.cur'
  'size_we.cur'     = 'Horz.cur'
  'size_nwse.cur'   = 'Dgn1.cur'
  'size_nesw.cur'   = 'Dgn2.cur'
  'move.cur'        = 'Move.cur'
  'up.cur'          = 'Alternate.cur'
  'link.cur'        = 'Link.cur'
}

function Get-ExtractionMarkerPath {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  return Join-Path $Path '.extraction-complete'
}

function Test-CursorFilePlausible {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
    return $false
  }

  $extension = [IO.Path]::GetExtension($Path).ToLowerInvariant()
  if ($extension -ne '.cur' -and $extension -ne '.ani') {
    return $false
  }

  return ((Get-Item -LiteralPath $Path).Length -gt 0)
}

function Save-BibataArchive {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Destination
  )

  try {
    Save-UrlIfMissing -Uri $bibataArchiveUri -Destination $Destination
  } catch {
    $message = $_.Exception.Message
    Remove-Item -LiteralPath $Destination -Force -ErrorAction SilentlyContinue
    throw "Unable to download Bibata cursor archive ${script:BibataCursorVersion}: $message"
  }
}

function Find-BibataCursorSourceDirectory {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  $expected = Join-Path $Path $script:BibataExpectedSourceDirectoryName
  if (Test-Path -LiteralPath $expected -PathType Container) {
    return $expected
  }

  throw "Expected Bibata cursor directory $expected was not found after extracting $script:BibataCursorVersion."
}

function Test-BibataExtractionComplete {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  if (-not (Test-Path -LiteralPath (Get-ExtractionMarkerPath -Path $Path) -PathType Leaf)) {
    return $false
  }

  try {
    $sourceDirectory = Find-BibataCursorSourceDirectory -Path $Path
  } catch {
    return $false
  }

  foreach ($targetFileName in $sourceCursorMap.Keys) {
    $sourcePath = Join-Path $sourceDirectory $sourceCursorMap[$targetFileName]
    if (-not (Test-CursorFilePlausible -Path $sourcePath)) {
      return $false
    }
  }

  return $true
}

function Clear-BibataArchiveCache {
  param(
    [Parameter(Mandatory = $true)]
    [string]$ZipPath,

    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  Remove-Item -LiteralPath $ZipPath -Force -ErrorAction SilentlyContinue
  Remove-Item -LiteralPath (Get-ExtractionMarkerPath -Path $Path) -Force -ErrorAction SilentlyContinue

  if (Test-Path -LiteralPath $Path -PathType Container) {
    Remove-Item -LiteralPath $Path -Recurse -Force
  }
}

function Expand-BibataArchiveIfNeeded {
  param(
    [Parameter(Mandatory = $true)]
    [string]$ZipPath,

    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  if (Test-BibataExtractionComplete -Path $Path) {
    Write-Host "Using extracted cursors $Path"
    return
  }

  for ($attempt = 1; $attempt -le 2; $attempt++) {
    if (Test-Path -LiteralPath $Path -PathType Container) {
      Write-Host "Clearing incomplete extracted cursors $Path"
      Remove-Item -LiteralPath $Path -Recurse -Force
    }

    Save-BibataArchive -Destination $ZipPath

    Write-Host 'Expanding Bibata Modern Ice cursors.'
    try {
      Expand-ZipToDirectory -ZipPath $ZipPath -Destination $Path
      New-Item -ItemType File -Path (Get-ExtractionMarkerPath -Path $Path) -Force | Out-Null

      if (Test-BibataExtractionComplete -Path $Path) {
        return
      }

      throw 'Archive did not extract all required cursor files.'
    } catch {
      $message = $_.Exception.Message
      Clear-BibataArchiveCache -ZipPath $ZipPath -Path $Path

      if ($attempt -lt 2) {
        Write-Host 'Cached Bibata archive is invalid. Downloading again.'
        continue
      }

      throw "Bibata cursor archive failed after retry: $message"
    }
  }
}

function Test-SameFileContent {
  param(
    [Parameter(Mandatory = $true)]
    [string]$SourcePath,

    [Parameter(Mandatory = $true)]
    [string]$TargetPath
  )

  if (-not (Test-Path -LiteralPath $TargetPath -PathType Leaf)) {
    return $false
  }

  $source = Get-Item -LiteralPath $SourcePath
  $target = Get-Item -LiteralPath $TargetPath
  if ($source.Length -ne $target.Length) {
    return $false
  }

  $sourceHash = (Get-FileHash -LiteralPath $SourcePath -Algorithm SHA256).Hash
  $targetHash = (Get-FileHash -LiteralPath $TargetPath -Algorithm SHA256).Hash
  return ($sourceHash -eq $targetHash)
}

function Install-CursorFile {
  param(
    [Parameter(Mandatory = $true)]
    [string]$SourcePath,

    [Parameter(Mandatory = $true)]
    [string]$TargetFileName
  )

  $targetPath = Join-Path $script:CursorRoot $TargetFileName
  if (Test-SameFileContent -SourcePath $SourcePath -TargetPath $targetPath) {
    Write-Host "Cursor file $targetPath is current."
    return
  }

  Copy-Item -LiteralPath $SourcePath -Destination $targetPath -Force
  Write-Host "Installed cursor file $targetPath"
}

function Set-CursorRegistryValue {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Name,

    [Parameter(Mandatory = $true)]
    [string]$Value
  )

  if ($script:NoActivate) {
    return
  }

  New-Item -Path $script:CursorRegistry -Force | Out-Null
  $property = Get-ItemProperty -Path $script:CursorRegistry -Name $Name -ErrorAction SilentlyContinue
  $current = $null
  if ($null -ne $property -and $null -ne $property.PSObject.Properties[$Name]) {
    $current = $property.PSObject.Properties[$Name].Value
  }

  if ($current -eq $Value) {
    return
  }

  New-ItemProperty -Path $script:CursorRegistry -Name $Name -Value $Value -PropertyType String -Force | Out-Null
  $script:CursorRegistryChanged = $true
  Write-Host "Set cursor role $Name"
}

function Update-CursorScheme {
  if ($script:NoActivate) {
    Write-Host 'Skipping cursor activation because -NoActivate was passed.'
    return
  }

  if (-not $script:CursorRegistryChanged) {
    Write-Host 'Cursor registry values are already current.'
    return
  }

  if (-not ('NativeMethods.CursorScheme' -as [type])) {
    Add-Type -TypeDefinition @'
namespace NativeMethods {
  using System;
  using System.Runtime.InteropServices;

  public static class CursorScheme {
    [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
    public static extern bool SystemParametersInfo(uint uiAction, uint uiParam, string pvParam, uint fWinIni);
  }
}
'@
  }

  $updated = [NativeMethods.CursorScheme]::SystemParametersInfo(0x0057, 0, $null, 0x0001 -bor 0x0002)
  if (-not $updated) {
    $lastWin32Error = [Runtime.InteropServices.Marshal]::GetLastWin32Error()
    if ($lastWin32Error -ne 0) {
      $win32Message = ([ComponentModel.Win32Exception]::new($lastWin32Error)).Message
      throw "Failed to refresh cursor scheme with SystemParametersInfo(SPI_SETCURSORS): Win32 error $lastWin32Error ($win32Message)."
    }

    throw 'Failed to refresh cursor scheme with SystemParametersInfo(SPI_SETCURSORS).'
  }

  Write-Host 'Refreshed cursor scheme.'
}

Expand-BibataArchiveIfNeeded -ZipPath $archivePath -Path $extractPath
$cursorSourceDirectory = Find-BibataCursorSourceDirectory -Path $extractPath

foreach ($targetFileName in ($sourceCursorMap.Keys | Sort-Object)) {
  $sourcePath = Join-Path $cursorSourceDirectory $sourceCursorMap[$targetFileName]
  Install-CursorFile -SourcePath $sourcePath -TargetFileName $targetFileName
}

foreach ($role in ($cursorMap.Keys | Sort-Object)) {
  $cursorPath = Join-Path $script:CursorRoot $cursorMap[$role]
  if (-not (Test-CursorFilePlausible -Path $cursorPath)) {
    throw "Cursor role $role points to missing or empty file $cursorPath."
  }

  Set-CursorRegistryValue -Name $role -Value $cursorPath
}

Update-CursorScheme
