# Tmux config derived from nix-config

set -g default-shell /usr/bin/zsh
set -g default-command "/usr/bin/zsh -l"

set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi
set -g clock-mode-style 24
set -g allow-passthrough on
set -ga update-environment "TERM"
set -ga update-environment "TERM_PROGRAM"

# Plugins
set-environment -gF TMUX_PLUGIN_MANAGER_PATH '#{?#{E:TMUX_PLUGIN_MANAGER_PATH},#{E:TMUX_PLUGIN_MANAGER_PATH},#{?#{E:XDG_CONFIG_HOME},#{E:XDG_CONFIG_HOME}/tmux/plugins/,#{E:HOME}/.config/tmux/plugins/}}'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-fahrenheit false
set -g @dracula-plugins "battery cpu-usage ram-usage time"
set -g @dracula-show-left-icon session
set -g @dracula-day-month true
set -g @dracula-military-time true
set -g @dracula-battery-label ""

# Initialize TPM
run-shell '#{E:TMUX_PLUGIN_MANAGER_PATH}tpm/tpm'
